name: Build and Push Docker image (frontend)

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types:
      - dispatch-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: make date tag 
      id: mkdatetag
      run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub 
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: frontend
        file: frontend/Dockerfile
        tags: glideinwms/gwms-frontend:3.7.5.osg35.el7-${{ steps.mkdatetag.outputs.dtag }}
